import type { ExtendedLanguageCode } from "@/types/common";

type CommonStrings = {
  [key in ExtendedLanguageCode]: {
    result: string;
    results: string;
  };
};

const strings: CommonStrings = {
  de: {
    result: "Ergebnis",
    results: "Ergebnisse",
  },
  es: {
    result: "resultado",
    results: "resultados",
  },
  eo: {
    result: "rezulto",
    results: "rezultoj",
  },
  et: {
    result: "tulemus",
    results: "tulemused",
  },
  fr: {
    result: "résultat",
    results: "résultats",
  },
  en: {
    result: "result",
    results: "results",
  },
  hu: {
    result: "eredmény",
    results: "eredmények",
  },
  nl: {
    result: "resultaat",
    results: "resultaten",
  },
  nx: {
    result: "kum",
    results: "kum",
  },
  pl: {
    result: "wynik",
    results: "wyniki",
  },
  pt: {
    result: "resultado",
    results: "resultados",
  },
  ru: {
    result: "результат",
    results: "результаты",
  },
  sv: {
    result: "resultat",
    results: "resultat",
  },
  tr: {
    result: "sonuç",
    results: "sonuçlar",
  },
};

export default strings;

export type PartOfSpeechType = {
  [key in ExtendedLanguageCode]: {
    [key: string]: string;
  };
};

export const PartOfSpeech: PartOfSpeechType = {
  de: {
    "vtr.": "transitives Verb",
    "n.": "Nomen",
    "num.": "Nummer",
    "pn.": "Pronomen",
    "adv.": "Adverb",
    "adj.": "Adjektiv",
    "vin.": "intransitives Verb",
    "inter.": "Interrogativ",
    "part.": "Partikel",
    "adp.": "Adposition",
    "adv., n.": "Adverb, Nomen",
    "vtrm.": "transitives Modalverb",
    "vim.": "intransitives Modalverb",
    "conj.": "Konjunktion",
    "sbd.": "Subordinator",
    "n., intj.": "Nomen, Interjektion",
    "intj.": "Interjektion",
    "part., intj.": "Partikel, Interjektion",
    "prop.n.": "Eigenname",
    "vin., intj.": "intransitives Verb, Interjektion",
    "adj., n.": "Adjektiv, Nomen",
    "adj., adv.": "Adjektiv, Adverb",
    "adj., intj.": "Adjektiv, Interjektion",
    "adv., intj.": "Adverb, Interjektion",
    "ph.": "Phrase",
    "adj., conj.": "Adjektiv, Konjunktion",
    "inter., intj.": "Interrogativ, Interjektion",
    "adv., conj.": "Adverb, Konjunktion",
    "vin., vtr.": "intransitives oder transitives Verb",
  },
  en: {
    "vtr.": "Transitive Verb",
    "n.": "Noun",
    "num.": "Number",
    "pn.": "Pronoun",
    "adv.": "Adverb",
    "adj.": "Adjective",
    "vin.": "Intransitive Verb",
    "inter.": "Interrogative",
    "part.": "Particle",
    "adp.": "Adposition",
    "adv., n.": "Adverb, Noun",
    "vtrm.": "Transitive Modal Verb",
    "vim.": "Intransitive Modal Verb",
    "conj.": "Conjunction",
    "sbd.": "Subordinator",
    "n., intj.": "Noun, Interjection",
    "intj.": "Interjection",
    "part., intj.": "Particle, Interjection",
    "prop.n.": "Proper Noun",
    "vin., intj.": "Intransitive Verb, Interjection",
    "adj., n.": "Adjective, Noun",
    "adj., adv.": "Adjective, Adverb",
    "adj., intj.": "Adjective, Interjection",
    "adv., intj.": "Adverb, Interjection",
    "ph.": "Phrase",
    "adj., conj.": "Adjective, Conjunction",
    "inter., intj.": "Interrogative, Interjection",
    "adv., conj.": "Adverb, Conjunction",
    "vin., vtr.": "Intransitive Or Transitive Verb",
  },
  eo: {
    "vtr.": "tranzitiva verbo",
    "n.": "substantivo",
    "num.": "numero",
    "pn.": "pronomo",
    "adv.": "adverbo",
    "adj.": "adjektivo",
    "vin.": "netranzitiva verbo",
    "inter.": "interrogativa vorto",
    "part.": "partiklo",
    "adp.": "adpozicio",
    "adv., n.": "adverbo, substantivo",
    "vtrm.": "tranzitiva modalverbo",
    "vim.": "netranzitiva modalverbo",
    "conj.": "konjunkcio",
    "sbd.": "subordinanto",
    "n., intj.": "substantivo, interjekcio",
    "intj.": "interjekcio",
    "part., intj.": "partiklo, interjekcio",
    "prop.n.": "propra nomo",
    "vin., intj.": "netranzitiva verbo, interjekcio",
    "adj., n.": "adjektivo, substantivo",
    "adj., adv.": "adjektivo, adverbo",
    "adj., intj.": "adjektivo, interjekcio",
    "adv., intj.": "adverbo, interjekcio",
    "ph.": "frazo",
    "adj., conj.": "adjektivo, konjunkcio",
    "inter., intj.": "interrogativa vorto, interjekcio",
    "adv., conj.": "adverbo, konjunkcio",
    "vin., vtr.": "netranzitiva aŭ tranzitiva verbo",
  },
  es: {
    "vtr.": "Verbo transitivo",
    "n.": "Nombre",
    "num.": "Número",
    "pn.": "Pronombre",
    "adv.": "Adverbio",
    "adj.": "Adjetivo",
    "vin.": "Verbo intransitivo",
    "inter.": "Interrogativo",
    "part.": "Partícula",
    "adp.": "Adposición",
    "adv., n.": "Adverbio, Nombre",
    "vtrm.": "Verbo modal transitivo",
    "vim.": "Verbo modal intransitivo",
    "conj.": "Conjunción",
    "sbd.": "Subordinador",
    "n., intj.": "Nombre, Interjección",
    "intj.": "Interjección",
    "part., intj.": "Partícula, Interjección",
    "prop.n.": "Nombre propio",
    "vin., intj.": "Verbo intransitivo, Interjección",
    "adj., n.": "Adjetivo, Nombre",
    "adj., adv.": "Adjetivo, Adverbio",
    "adj., intj.": "Adjetivo, Interjección",
    "adv., intj.": "Adverbio, Interjección",
    "ph.": "Frase",
    "adj., conj.": "Adjetivo, Conjunción",
    "inter., intj.": "Interrogativo, Interjección",
    "adv., conj.": "Adverbio, Conjunción",
    "vin., vtr.": "Verbo intransitivo o transitivo",
  },
  et: {
    "vtr.": "transitiivne verb",
    "n.": "nimisõna",
    "num.": "number",
    "pn.": "asemäärsõna",
    "adv.": "adverb",
    "adj.": "omadussõna",
    "vin.": "intransitiivne verb",
    "inter.": "interrogatiiv",
    "part.": "partikkel",
    "adp.": "adpositsioon",
    "adv., n.": "adverb, nimisõna",
    "vtrm.": "transitiivne modaalverb",
    "vim.": "intransitiivne modaalverb",
    "conj.": "sidesõna",
    "sbd.": "subordinatiiv",
    "n., intj.": "nimisõna, interjektsioon",
    "intj.": "interjektsioon",
    "part., intj.": "partikkel, interjektsioon",
    "prop.n.": "pärisnimi",
    "vin., intj.": "intransitiivne verb, interjektsioon",
    "adj., n.": "omadussõna, nimisõna",
    "adj., adv.": "omadussõna, adverb",
    "adj., intj.": "omadussõna, interjektsioon",
    "adv., intj.": "adverb, interjektsioon",
    "ph.": "fraas",
    "adj., conj.": "omadussõna, sidesõna",
    "inter., intj.": "interrogatiiv, interjektsioon",
    "adv., conj.": "adverb, sidesõna",
    "vin., vtr.": "intransitiivne või transitiivne verb",
  },
  fr: {
    "vtr.": "Verbe transitif",
    "n.": "Nom",
    "num.": "Nombre",
    "pn.": "Pronom",
    "adv.": "Adverbe",
    "adj.": "Adjectif",
    "vin.": "Verbe intransitif",
    "inter.": "Interrogatif",
    "part.": "Particule",
    "adp.": "Adposition",
    "adv., n.": "Adverbe, Nom",
    "vtrm.": "Verbe modal transitif",
    "vim.": "Verbe modal intransitif",
    "conj.": "Conjonction",
    "sbd.": "Subordonnant",
    "n., intj.": "Nom, Interjection",
    "intj.": "Interjection",
    "part., intj.": "Particule, Interjection",
    "prop.n.": "Nom propre",
    "vin., intj.": "Verbe intransitif, Interjection",
    "adj., n.": "Adjectif, Nom",
    "adj., adv.": "Adjectif, Adverbe",
    "adj., intj.": "Adjectif, Interjection",
    "adv., intj.": "Adverbe, Interjection",
    "ph.": "Phrase",
    "adj., conj.": "Adjectif, Conjonction",
    "inter., intj.": "Interrogatif, Interjection",
    "adv., conj.": "Adverbe, Conjonction",
    "vin., vtr.": "Verbe intransitif ou transitif",
  },
  hu: {
    "vtr.": "transitives Verb",
    "n.": "Nomen",
    "num.": "Nummer",
    "pn.": "Pronomen",
    "adv.": "Adverb",
    "adj.": "Adjektiv",
    "vin.": "intransitives Verb",
    "inter.": "Interrogativ",
    "part.": "Partikel",
    "adp.": "Adposition",
    "adv., n.": "Adverb, Nomen",
    "vtrm.": "transitives Modalverb",
    "vim.": "intransitives Modalverb",
    "conj.": "Konjunktion",
    "sbd.": "Subordinator",
    "n., intj.": "Nomen, Interjektion",
    "intj.": "Interjektion",
    "part., intj.": "Partikel, Interjektion",
    "prop.n.": "Eigenname",
    "vin., intj.": "intransitives Verb, Interjektion",
    "adj., n.": "Adjektiv, Nomen",
    "adj., adv.": "Adjektiv, Adverb",
    "adj., intj.": "Adjektiv, Interjektion",
    "adv., intj.": "Adverb, Interjektion",
    "ph.": "Phrase",
    "adj., conj.": "Adjektiv, Konjunktion",
    "inter., intj.": "Interrogativ, Interjektion",
    "adv., conj.": "Adverb, Konjunktion",
    "vin., vtr.": "intransitives oder transitives Verb",
  },
  nl: {
    "vtr.": "Transitief werkwoord",
    "n.": "Naamwoord",
    "num.": "Nummer",
    "pn.": "Voornaamwoord",
    "adv.": "Bijwoord",
    "adj.": "Bijvoeglijk naamwoord",
    "vin.": "Intransitief werkwoord",
    "inter.": "Vragend",
    "part.": "Deeltje",
    "adp.": "Adpositie",
    "adv., n.": "Bijwoord, Naamwoord",
    "vtrm.": "Transitief modaal werkwoord",
    "vim.": "Intransitief modaal werkwoord",
    "conj.": "Voegwoord",
    "sbd.": "Subordinator",
    "n., intj.": "Naamwoord, Interjectie",
    "intj.": "Interjectie",
    "part., intj.": "Deeltje, Interjectie",
    "prop.n.": "Eigennaam",
    "vin., intj.": "Intransitief werkwoord, Interjectie",
    "adj., n.": "Bijvoeglijk naamwoord, Naamwoord",
    "adj., adv.": "Bijvoeglijk naamwoord, Bijwoord",
    "adj., intj.": "Bijvoeglijk naamwoord, Interjectie",
    "adv., intj.": "Bijwoord, Interjectie",
    "ph.": "Zin",
    "adj., conj.": "Bijvoeglijk naamwoord, Voegwoord",
    "inter., intj.": "Vragend, Interjectie",
    "adv., conj.": "Bijwoord, Voegwoord",
    "vin., vtr.": "Intransitief of transitief werkwoord",
  },
  nx: {
    // TODO: Translate
    "vtr.": "Transitive Verb",
    "n.": "Noun",
    "num.": "Number",
    "pn.": "Pronoun",
    "adv.": "Adverb",
    "adj.": "Adjective",
    "vin.": "Intransitive Verb",
    "inter.": "Interrogative",
    "part.": "Particle",
    "adp.": "Adposition",
    "adv., n.": "Adverb, Noun",
    "vtrm.": "Transitive Modal Verb",
    "vim.": "Intransitive Modal Verb",
    "conj.": "Conjunction",
    "sbd.": "Subordinator",
    "n., intj.": "Noun, Interjection",
    "intj.": "Interjection",
    "part., intj.": "Particle, Interjection",
    "prop.n.": "Proper Noun",
    "vin., intj.": "Intransitive Verb, Interjection",
    "adj., n.": "Adjective, Noun",
    "adj., adv.": "Adjective, Adverb",
    "adj., intj.": "Adjective, Interjection",
    "adv., intj.": "Adverb, Interjection",
    "ph.": "Phrase",
    "adj., conj.": "Adjective, Conjunction",
    "inter., intj.": "Interrogative, Interjection",
    "adv., conj.": "Adverb, Conjunction",
    "vin., vtr.": "Intransitive Or Transitive Verb",
  },
  pl: {
    "vtr.": "czasownik przechodni",
    "n.": "rzeczownik",
    "num.": "liczebnik",
    "pn.": "zaimek",
    "adv.": "przysłówek",
    "adj.": "przymiotnik",
    "vin.": "czasownik nieprzechodni",
    "inter.": "zaimek pytający",
    "part.": "cząstka",
    "adp.": "przyimek",
    "adv., n.": "przysłówek, rzeczownik",
    "vtrm.": "czasownik modalny przechodni",
    "vim.": "czasownik modalny nieprzechodni",
    "conj.": "spójnik",
    "sbd.": "spójnik podrzędny",
    "n., intj.": "rzeczownik, wykrzyknik",
    "intj.": "wykrzyknik",
    "part., intj.": "cząstka, wykrzyknik",
    "prop.n.": "nazwa własna",
    "vin., intj.": "czasownik nieprzechodni, wykrzyknik",
    "adj., n.": "przymiotnik, rzeczownik",
    "adj., adv.": "przymiotnik, przysłówek",
    "adj., intj.": "przymiotnik, wykrzyknik",
    "adv., intj.": "przysłówek, wykrzyknik",
    "ph.": "wyrażenie",
    "adj., conj.": "przymiotnik, spójnik",
    "inter., intj.": "zaimek pytający, wykrzyknik",
    "adv., conj.": "przysłówek, spójnik",
    "vin., vtr.": "czasownik nieprzechodni lub przechodni",
  },
  pt: {
    "vtr.": "Verbo Transitivo",
    "n.": "Substantivo",
    "num.": "Número",
    "pn.": "Pronome",
    "adv.": "Advérbio",
    "adj.": "Adjetivo",
    "vin.": "Verbo intransitivo",
    "inter.": "Interrogativo",
    "part.": "Partícula",
    "adp.": "Adposição",
    "adv., n.": "Advérbio, Substantivo",
    "vtrm.": "Verbo Modal Transitivo",
    "vim.": "Verbo Modal Intransitivo",
    "conj.": "Conjunção",
    "sbd.": "Subordinador",
    "n., intj.": "Substantivo, Interjeição",
    "intj.": "Interjeição",
    "part., intj.": "Partícula, Interjeição",
    "prop.n.": "Nome Próprio",
    "vin., intj.": "Verbo intransitivo, Interjeição",
    "adj., n.": "Adjetivo, Substantivo",
    "adj., adv.": "Adjetivo, Advérbio",
    "adj., intj.": "Adjetivo, Interjeição",
    "adv., intj.": "Advérbio, Interjeição",
    "ph.": "Frase",
    "adj., conj.": "Adjetivo, Conjunção",
    "inter., intj.": "Interrogativo, Interjeição",
    "adv., conj.": "Advérbio, Conjunção",
    "vin., vtr.": "Verbo Intransitivo ou Transitivo",
  },
  ru: {
    "vtr.": "переходный глагол",
    "n.": "имя существительное",
    "num.": "число",
    "pn.": "местоимение",
    "adv.": "наречие",
    "adj.": "прилагательное",
    "vin.": "непереходный глагол",
    "inter.": "вопросительное слово",
    "part.": "частица",
    "adp.": "предлог",
    "adv., n.": "наречие, имя существительное",
    "vtrm.": "переходный модальный глагол",
    "vim.": "непереходный модальный глагол",
    "conj.": "союз",
    "sbd.": "подчинительный союз",
    "n., intj.": "имя существительное, междометие",
    "intj.": "междометие",
    "part., intj.": "частица, междометие",
    "prop.n.": "имя собственное",
    "vin., intj.": "непереходный глагол, междометие",
    "adj., n.": "прилагательное, имя существительное",
    "adj., adv.": "прилагательное, наречие",
    "adj., intj.": "прилагательное, междометие",
    "adv., intj.": "наречие, междометие",
    "ph.": "фраза",
    "adj., conj.": "прилагательное, союз",
    "inter., intj.": "вопросительное слово, междометие",
    "adv., conj.": "наречие, союз",
    "vin., vtr.": "непереходный или переходный глагол",
  },
  sv: {
    "vtr.": "transitivt verb",
    "n.": "substantiv",
    "num.": "nummer",
    "pn.": "pronomen",
    "adv.": "adverb",
    "adj.": "adjektiv",
    "vin.": "intransitivt verb",
    "inter.": "interrogativ",
    "part.": "partikel",
    "adp.": "adposition",
    "adv., n.": "adverb, substantiv",
    "vtrm.": "transitivt modalverb",
    "vim.": "intransitivt modalverb",
    "conj.": "konjunktion",
    "sbd.": "subordinator",
    "n., intj.": "substantiv, interjektion",
    "intj.": "interjektion",
    "part., intj.": "partikel, interjektion",
    "prop.n.": "egennamn",
    "vin., intj.": "intransitivt verb, interjektion",
    "adj., n.": "adjektiv, substantiv",
    "adj., adv.": "adjektiv, adverb",
    "adj., intj.": "adjektiv, interjektion",
    "adv., intj.": "adverb, interjektion",
    "ph.": "fras",
    "adj., conj.": "adjektiv, konjunktion",
    "inter., intj.": "interrogativ, interjektion",
    "adv., conj.": "adverb, konjunktion",
    "vin., vtr.": "intransitivt eller transitivt verb",
  },
  tr: {
    "vtr.": "Edat",
    "n.": "İsim",
    "num.": "Sayı",
    "pn.": "Zamir",
    "adv.": "Zarf",
    "adj.": "Sıfat",
    "vin.": "Edat",
    "inter.": "Soru",
    "part.": "Parça",
    "adp.": "Edat",
    "adv., n.": "Zarf, İsim",
    "vtrm.": "Edat",
    "vim.": "Edat",
    "conj.": "Bağlaç",
    "sbd.": "Edat",
    "n., intj.": "İsim, Ünlem",
    "intj.": "Ünlem",
    "part., intj.": "Parça, Ünlem",
    "prop.n.": "Özel isim",
    "vin., intj.": "Edat",
    "adj., n.": "Sıfat, İsim",
    "adj., adv.": "Sıfat, Zarf",
    "adj., intj.": "Sıfat, Ünlem",
    "adv., intj.": "Zarf, Ünlem",
    "ph.": "İfade",
    "adj., conj.": "Sıfat, Bağlaç",
    "inter., intj.": "Soru, Ünlem",
    "adv., conj.": "Zarf, Bağlaç",
    "vin., vtr.": "Edat",
  },
};
