import { ListMenu, WhatValue } from "@/types/list";
import { ExtendedLanguageCode } from "./settings";

export const WhatValues: WhatValue[] = [
  "pos",
  "word",
  "words",
  "syllables",
  "stress",
  "length",
];

type ListStrings = {
  [key in ExtendedLanguageCode]: {
    list: string;
    listOptions: string;
    listMenu: ListMenu;
    and: string;
    go: string;
    noResults: string;
  };
};

const strings: ListStrings = {
  de: {
    list: "Liste",
    listOptions: "LISTENOPTIONEN",
    listMenu: {
      whatValues: [
        { value: "pos", description: "Wortart ist, hat, etc." },
        { value: "word", description: "beginnt mit, endet mit, hat, etc." },
        {
          value: "words",
          description: "nach Veröffentlichung, erstes oder letztes",
        },
        { value: "syllables", description: "Anzahl der Silben" },
        { value: "stress", description: "betonte Silbenposition" },
        { value: "length", description: "Länge des Wortes in Phonemen" },
      ],
      condValues: {
        pos: [
          { value: "starts", description: "beginnt mit" },
          { value: "ends", description: "endet mit" },
          { value: "is", description: "ist" },
          { value: "has", description: "hat" },
          { value: "like", description: "ist wie" },
          { value: "not-starts", description: "beginnt nicht mit" },
          { value: "not-ends", description: "endet nicht mit" },
          { value: "not-is", description: "ist nicht" },
          { value: "not-has", description: "hat nicht" },
          { value: "not-like", description: "ist nicht wie" },
        ],
        word: [
          { value: "starts", description: "beginnt mit" },
          { value: "ends", description: "endet mit" },
          { value: "has", description: "hat" },
          { value: "like", description: "ist wie" },
          { value: "not-starts", description: "beginnt nicht mit" },
          { value: "not-ends", description: "endet nicht mit" },
          { value: "not-has", description: "hat nicht" },
          { value: "not-like", description: "ist nicht wie" },
        ],
        words: [
          { value: "first", description: "älteste Wörter" },
          { value: "last", description: "neueste Wörter" },
        ],
        syllables: [
          { value: "<", description: "kleiner als" },
          { value: "<=", description: "kleiner als oder gleich" },
          { value: "=", description: "gleich" },
          { value: ">=", description: "größer als oder gleich" },
          { value: ">", description: "größer als" },
          { value: "!=", description: "ungleich" },
        ],
        stress: [
          { value: "<", description: "kleiner als" },
          { value: "<=", description: "kleiner als oder gleich" },
          { value: "=", description: "gleich" },
          { value: ">=", description: "größer als oder gleich" },
          { value: ">", description: "größer als" },
          { value: "!=", description: "ungleich" },
        ],
        length: [
          { value: "<", description: "kleiner als" },
          { value: "<=", description: "kleiner als oder gleich" },
          { value: "=", description: "gleich" },
          { value: ">=", description: "größer als oder gleich" },
          { value: ">", description: "größer als" },
          { value: "!=", description: "ungleich" },
        ],
      },
    } as ListMenu,
    and: "UND...",
    go: "LOS",
    noResults: "keine Ergebnisse",
  },
  es: {
    list: "Lista",
    listOptions: "OPCIONES DE LISTA",
    listMenu: {
      whatValues: [
        { value: "pos", description: "parte del discurso es, tiene, etc." },
        {
          value: "word",
          description: "comienza con, termina con, tiene, etc.",
        },
        {
          value: "words",
          description: "en orden de lanzamiento, primero o último",
        },
        { value: "syllables", description: "número de sílabas" },
        { value: "stress", description: "posición de la sílaba acentuada" },
        { value: "length", description: "longitud de la palabra en fonemas" },
      ],
      condValues: {
        pos: [
          { value: "starts", description: "comienza con" },
          { value: "ends", description: "termina con" },
          { value: "is", description: "es" },
          { value: "has", description: "tiene" },
          { value: "like", description: "es como" },
          { value: "not-starts", description: "no comienza con" },
          { value: "not-ends", description: "no termina con" },
          { value: "not-is", description: "no es" },
          { value: "not-has", description: "no tiene" },
          { value: "not-like", description: "no es como" },
        ],
        word: [
          { value: "starts", description: "comienza con" },
          { value: "ends", description: "termina con" },
          { value: "has", description: "tiene" },
          { value: "like", description: "es como" },
          { value: "not-starts", description: "no comienza con" },
          { value: "not-ends", description: "no termina con" },
          { value: "not-has", description: "no tiene" },
          { value: "not-like", description: "no es como" },
        ],
        words: [
          { value: "first", description: "palabras más antiguas" },
          { value: "last", description: "palabras más nuevas" },
        ],
        syllables: [
          { value: "<", description: "menos que" },
          { value: "<=", description: "menos que o igual a" },
          { value: "=", description: "igual a" },
          { value: ">=", description: "mayor que o igual a" },
          { value: ">", description: "mayor que" },
          { value: "!=", description: "no es igual a" },
        ],
        stress: [
          { value: "<", description: "menos que" },
          { value: "<=", description: "menos que o igual a" },
          { value: "=", description: "igual a" },
          { value: ">=", description: "mayor que o igual a" },
          { value: ">", description: "mayor que" },
          { value: "!=", description: "no es igual a" },
        ],
        length: [
          { value: "<", description: "menos que" },
          { value: "<=", description: "menos que o igual a" },
          { value: "=", description: "igual a" },
          { value: ">=", description: "mayor que o igual a" },
          { value: ">", description: "mayor que" },
          { value: "!=", description: "no es igual a" },
        ],
      },
    } as ListMenu,
    and: "Y...",
    go: "IR",
    noResults: "sin resultados",
  },
  et: {
    list: "Nimekiri",
    listOptions: "LOENDI VALIKUD",
    listMenu: {
      whatValues: [
        { value: "pos", description: "sõnaliik on, on, jne." },
        { value: "word", description: "algab, lõpeb, on, jne." },
        {
          value: "words",
          description: "väljalaske järjekorras, esimene või viimane",
        },
        { value: "syllables", description: "silpide arv" },
        { value: "stress", description: "rõhutatud silbi asend" },
        { value: "length", description: "sõna pikkus foneemides" },
      ],
      condValues: {
        pos: [
          { value: "starts", description: "algab" },
          { value: "ends", description: "lõpeb" },
          { value: "is", description: "on" },
          { value: "has", description: "on" },
          { value: "like", description: "on nagu" },
          { value: "not-starts", description: "ei alga" },
          { value: "not-ends", description: "ei lõpe" },
          { value: "not-is", description: "pole" },
          { value: "not-has", description: "pole" },
          { value: "not-like", description: "pole nagu" },
        ],
        word: [
          { value: "starts", description: "algab" },
          { value: "ends", description: "lõpeb" },
          { value: "has", description: "on" },
          { value: "like", description: "on nagu" },
          { value: "not-starts", description: "ei alga" },
          { value: "not-ends", description: "ei lõpe" },
          { value: "not-has", description: "pole" },
          { value: "not-like", description: "pole nagu" },
        ],
        words: [
          { value: "first", description: "vanimad sõnad" },
          { value: "last", description: "uusimad sõnad" },
        ],
        syllables: [
          { value: "<", description: "väiksem kui" },
          { value: "<=", description: "väiksem kui või võrdne" },
          { value: "=", description: "võrdne" },
          { value: ">=", description: "suurem kui või võrdne" },
          { value: ">", description: "suurem kui" },
          { value: "!=", description: "pole võrdne" },
        ],
        stress: [
          { value: "<", description: "väiksem kui" },
          { value: "<=", description: "väiksem kui või võrdne" },
          { value: "=", description: "võrdne" },
          { value: ">=", description: "suurem kui või võrdne" },
          { value: ">", description: "suurem kui" },
          { value: "!=", description: "pole võrdne" },
        ],
        length: [
          { value: "<", description: "väiksem kui" },
          { value: "<=", description: "väiksem kui või võrdne" },
          { value: "=", description: "võrdne" },
          { value: ">=", description: "suurem kui või võrdne" },
          { value: ">", description: "suurem kui" },
          { value: "!=", description: "pole võrdne" },
        ],
      },
    } as ListMenu,
    and: "JA...",
    go: "MINNA",
    noResults: "tulemusi pole",
  },
  en: {
    list: "List",
    listOptions: "LIST OPTIONS",
    listMenu: {
      whatValues: [
        { value: "pos", description: "part of speech is, has, etc." },
        { value: "word", description: "starts with, ends with, has, etc." },
        { value: "words", description: "in order of release, first or last" },
        { value: "syllables", description: "number of syllables" },
        { value: "stress", description: "stressed syllable position" },
        { value: "length", description: "length of the word in phonemes" },
      ],
      condValues: {
        pos: [
          { value: "starts", description: "starts with" },
          { value: "ends", description: "ends with" },
          { value: "is", description: "is" },
          { value: "has", description: "has" },
          { value: "like", description: "is like" },
          { value: "not-starts", description: "does not start with" },
          { value: "not-ends", description: "does not end with" },
          { value: "not-is", description: "is not" },
          { value: "not-has", description: "does not have" },
          { value: "not-like", description: "is not like" },
        ],
        word: [
          { value: "starts", description: "starts with" },
          { value: "ends", description: "ends with" },
          { value: "has", description: "has" },
          { value: "like", description: "is like" },
          { value: "not-starts", description: "does not start with" },
          { value: "not-ends", description: "does not end with" },
          { value: "not-has", description: "does not have" },
          { value: "not-like", description: "is not like" },
        ],
        words: [
          { value: "first", description: "oldest words" },
          { value: "last", description: "newest words" },
        ],
        syllables: [
          { value: "<", description: "less than" },
          { value: "<=", description: "less than or equal to" },
          { value: "=", description: "equal to" },
          { value: ">=", description: "greater than or equal to" },
          { value: ">", description: "greater than" },
          { value: "!=", description: "not equal to" },
        ],
        stress: [
          { value: "<", description: "less than" },
          { value: "<=", description: "less than or equal to" },
          { value: "=", description: "equal to" },
          { value: ">=", description: "greater than or equal to" },
          { value: ">", description: "greater than" },
          { value: "!=", description: "not equal to" },
        ],
        length: [
          { value: "<", description: "less than" },
          { value: "<=", description: "less than or equal to" },
          { value: "=", description: "equal to" },
          { value: ">=", description: "greater than or equal to" },
          { value: ">", description: "greater than" },
          { value: "!=", description: "not equal to" },
        ],
      },
    } as ListMenu,
    and: "AND...",
    go: "GO",
    noResults: "no results",
  },
  fr: {
    list: "Liste",
    listOptions: "OPTIONS DE LISTE",
    listMenu: {
      whatValues: [
        { value: "pos", description: "partie du discours est, a, etc." },
        { value: "word", description: "commence par, se termine par, a, etc." },
        {
          value: "words",
          description: "dans l'ordre de sortie, premier ou dernier",
        },
        { value: "syllables", description: "nombre de syllabes" },
        { value: "stress", description: "position de la syllabe accentuée" },
        { value: "length", description: "longueur du mot en phonèmes" },
      ],
      condValues: {
        pos: [
          { value: "starts", description: "commence par" },
          { value: "ends", description: "se termine par" },
          { value: "is", description: "est" },
          { value: "has", description: "a" },
          { value: "like", description: "est comme" },
          { value: "not-starts", description: "ne commence pas par" },
          { value: "not-ends", description: "ne se termine pas par" },
          { value: "not-is", description: "n'est pas" },
          { value: "not-has", description: "n'a pas" },
          { value: "not-like", description: "n'est pas comme" },
        ],
        word: [
          { value: "starts", description: "commence par" },
          { value: "ends", description: "se termine par" },
          { value: "has", description: "a" },
          { value: "like", description: "est comme" },
          { value: "not-starts", description: "ne commence pas par" },
          { value: "not-ends", description: "ne se termine pas par" },
          { value: "not-has", description: "n'a pas" },
          { value: "not-like", description: "n'est pas comme" },
        ],
        words: [
          { value: "first", description: "mots les plus anciens" },
          { value: "last", description: "mots les plus récents" },
        ],
        syllables: [
          { value: "<", description: "moins que" },
          { value: "<=", description: "moins que ou égal à" },
          { value: "=", description: "égal à" },
          { value: ">=", description: "supérieur ou égal à" },
          { value: ">", description: "supérieur à" },
          { value: "!=", description: "pas égal à" },
        ],
        stress: [
          { value: "<", description: "moins que" },
          { value: "<=", description: "moins que ou égal à" },
          { value: "=", description: "égal à" },
          { value: ">=", description: "supérieur ou égal à" },
          { value: ">", description: "supérieur à" },
          { value: "!=", description: "pas égal à" },
        ],
        length: [
          { value: "<", description: "moins que" },
          { value: "<=", description: "moins que ou égal à" },
          { value: "=", description: "égal à" },
          { value: ">=", description: "supérieur ou égal à" },
          { value: ">", description: "supérieur à" },
          { value: "!=", description: "pas égal à" },
        ],
      },
    } as ListMenu,
    and: "ET...",
    go: "ALLER",
    noResults: "pas de résultats",
  },
  hu: {
    list: "Lista",
    listOptions: "LISTA BEÁLLÍTÁSAI",
    listMenu: {
      whatValues: [
        { value: "pos", description: "szófaj, van, stb." },
        { value: "word", description: "kezdődik, végződik, van, stb." },
        { value: "words", description: "kiadási sorrendben, első vagy utolsó" },
        { value: "syllables", description: "szótagok száma" },
        { value: "stress", description: "kiemelt szótag pozíció" },
        { value: "length", description: "a szó hossza fonémákban" },
      ],
      condValues: {
        pos: [
          { value: "starts", description: "kezdődik" },
          { value: "ends", description: "végződik" },
          { value: "is", description: "van" },
          { value: "has", description: "van" },
          { value: "like", description: "olyan, mint" },
          { value: "not-starts", description: "nem kezdődik" },
          { value: "not-ends", description: "nem végződik" },
          { value: "not-is", description: "nincs" },
          { value: "not-has", description: "nincs" },
          { value: "not-like", description: "nem olyan, mint" },
        ],
        word: [
          { value: "starts", description: "kezdődik" },
          { value: "ends", description: "végződik" },
          { value: "has", description: "van" },
          { value: "like", description: "olyan, mint" },
          { value: "not-starts", description: "nem kezdődik" },
          { value: "not-ends", description: "nem végződik" },
          { value: "not-has", description: "nincs" },
          { value: "not-like", description: "nem olyan, mint" },
        ],
        words: [
          { value: "first", description: "legrégebbi szavak" },
          { value: "last", description: "legújabb szavak" },
        ],
        syllables: [
          { value: "<", description: "kisebb, mint" },
          { value: "<=", description: "kisebb vagy egyenlő" },
          { value: "=", description: "egyenlő" },
          { value: ">=", description: "nagyobb vagy egyenlő" },
          { value: ">", description: "nagyobb, mint" },
          { value: "!=", description: "nem egyenlő" },
        ],
        stress: [
          { value: "<", description: "kisebb, mint" },
          { value: "<=", description: "kisebb vagy egyenlő" },
          { value: "=", description: "egyenlő" },
          { value: ">=", description: "nagyobb vagy egyenlő" },
          { value: ">", description: "nagyobb, mint" },
          { value: "!=", description: "nem egyenlő" },
        ],
        length: [
          { value: "<", description: "kisebb, mint" },
          { value: "<=", description: "kisebb vagy egyenlő" },
          { value: "=", description: "egyenlő" },
          { value: ">=", description: "nagyobb vagy egyenlő" },
          { value: ">", description: "nagyobb, mint" },
          { value: "!=", description: "nem egyenlő" },
        ],
      },
    } as ListMenu,
    and: "ÉS...",
    go: "MEGY",
    noResults: "nincs találat",
  },
  nl: {
    list: "Lijst",
    listOptions: "LIJSTOPTIES",
    listMenu: {
      whatValues: [
        { value: "pos", description: "woordsoort is, heeft, etc." },
        { value: "word", description: "begint met, eindigt met, heeft, etc." },
        {
          value: "words",
          description: "in volgorde van release, eerste of laatste",
        },
        { value: "syllables", description: "aantal lettergrepen" },
        { value: "stress", description: "beklemtoonde lettergreep positie" },
        { value: "length", description: "lengte van het woord in fonemen" },
      ],
      condValues: {
        pos: [
          { value: "starts", description: "begint met" },
          { value: "ends", description: "eindigt met" },
          { value: "is", description: "is" },
          { value: "has", description: "heeft" },
          { value: "like", description: "is als" },
          { value: "not-starts", description: "begint niet met" },
          { value: "not-ends", description: "eindigt niet met" },
          { value: "not-is", description: "is niet" },
          { value: "not-has", description: "heeft niet" },
          { value: "not-like", description: "is niet als" },
        ],
        word: [
          { value: "starts", description: "begint met" },
          { value: "ends", description: "eindigt met" },
          { value: "has", description: "heeft" },
          { value: "like", description: "is als" },
          { value: "not-starts", description: "begint niet met" },
          { value: "not-ends", description: "eindigt niet met" },
          { value: "not-has", description: "heeft niet" },
          { value: "not-like", description: "is niet als" },
        ],
        words: [
          { value: "first", description: "oudste woorden" },
          { value: "last", description: "nieuwste woorden" },
        ],
        syllables: [
          { value: "<", description: "minder dan" },
          { value: "<=", description: "minder dan of gelijk aan" },
          { value: "=", description: "gelijk aan" },
          { value: ">=", description: "groter dan of gelijk aan" },
          { value: ">", description: "groter dan" },
          { value: "!=", description: "niet gelijk aan" },
        ],
        stress: [
          { value: "<", description: "minder dan" },
          { value: "<=", description: "minder dan of gelijk aan" },
          { value: "=", description: "gelijk aan" },
          { value: ">=", description: "groter dan of gelijk aan" },
          { value: ">", description: "groter dan" },
          { value: "!=", description: "niet gelijk aan" },
        ],
        length: [
          { value: "<", description: "minder dan" },
          { value: "<=", description: "minder dan of gelijk aan" },
          { value: "=", description: "gelijk aan" },
          { value: ">=", description: "groter dan of gelijk aan" },
          { value: ">", description: "groter dan" },
          { value: "!=", description: "niet gelijk aan" },
        ],
      },
    } as ListMenu,
    and: "EN...",
    go: "GAAN",
    noResults: "geen resultaten",
  },
  nx: {
    list: "sna'o",
    listOptions: "tìftxey sna'oä",
    listMenu: {
      whatValues: [
        { value: "pos", description: "fnelì'u lu, sl." },
        { value: "word", description: "sngä'i fa, 'i'a fa, sl." },
        { value: "words", description: "ìlä kewan, 'awve fu syen" },
        { value: "syllables", description: "holpxay lì'kongä" },
        { value: "stress", description: "txura lì'kongä tseng" },
        { value: "length", description: "ngimpup lì'uä (ìlä flltxepam)" },
      ],
      condValues: {
        pos: [
          { value: "starts", description: "sngä'i fa" },
          { value: "ends", description: "'i'a fa" },
          { value: "is", description: "lu" },
          { value: "has", description: "nga'" },
          { value: "like", description: "lu pxel" },
          { value: "not-starts", description: "ke sngä'i fa" },
          { value: "not-ends", description: "ke 'i'a fa" },
          { value: "not-is", description: "ke lu" },
          { value: "not-has", description: "ke nga'" },
          { value: "not-like", description: "ke lu pxel" },
        ],
        word: [
          { value: "starts", description: "sngä'i fa" },
          { value: "ends", description: "'i'a fa" },
          { value: "has", description: "nga'" },
          { value: "like", description: "lu pxel" },
          { value: "not-starts", description: "ke sngä'i fa" },
          { value: "not-ends", description: "ke 'i'a fa" },
          { value: "not-has", description: "ke nga'" },
          { value: "not-like", description: "ke lu pxel" },
        ],
        words: [
          { value: "first", description: "lì'u alal frato" },
          { value: "last", description: "lì'u amip frato" },
        ],
        syllables: [
          { value: "<", description: "hì'i to" },
          { value: "<=", description: "hì'i to fu teng" },
          { value: "=", description: "teng" },
          { value: ">=", description: "apxa to fu teng" },
          { value: ">", description: "apxa to" },
          { value: "!=", description: "keteng" },
        ],
        stress: [
          { value: "<", description: "hì'i to" },
          { value: "<=", description: "hì'i to fu teng" },
          { value: "=", description: "teng" },
          { value: ">=", description: "apxa to fu teng" },
          { value: ">", description: "apxa to" },
          { value: "!=", description: "keteng" },
        ],
        length: [
          { value: "<", description: "hì'i to" },
          { value: "<=", description: "hì'i to fu teng" },
          { value: "=", description: "teng" },
          { value: ">=", description: "apxa to fu teng" },
          { value: ">", description: "apxa to" },
          { value: "!=", description: "keteng" },
        ],
      },
    } as ListMenu,
    and: "ulte...",
    go: "kä",
    noResults: "kea kum",
  },
  pl: {
    list: "Lista",
    listOptions: "OPCJE LISTY",
    listMenu: {
      whatValues: [
        { value: "pos", description: "część mowy jest, ma, itp." },
        { value: "word", description: "zaczyna się, kończy się, ma, itp." },
        {
          value: "words",
          description: "w kolejności wydania, pierwszy lub ostatni",
        },
        { value: "syllables", description: "liczba sylab" },
        { value: "stress", description: "pozycja akcentowanej sylaby" },
        { value: "length", description: "długość słowa w fonemach" },
      ],
      condValues: {
        pos: [
          { value: "starts", description: "zaczyna się" },
          { value: "ends", description: "kończy się" },
          { value: "is", description: "jest" },
          { value: "has", description: "ma" },
          { value: "like", description: "jest jak" },
          { value: "not-starts", description: "nie zaczyna się" },
          { value: "not-ends", description: "nie kończy się" },
          { value: "not-is", description: "nie jest" },
          { value: "not-has", description: "nie ma" },
          { value: "not-like", description: "nie jest jak" },
        ],
        word: [
          { value: "starts", description: "zaczyna się" },
          { value: "ends", description: "kończy się" },
          { value: "has", description: "ma" },
          { value: "like", description: "jest jak" },
          { value: "not-starts", description: "nie zaczyna się" },
          { value: "not-ends", description: "nie kończy się" },
          { value: "not-has", description: "nie ma" },
          { value: "not-like", description: "nie jest jak" },
        ],
        words: [
          { value: "first", description: "najstarsze słowa" },
          { value: "last", description: "najnowsze słowa" },
        ],
        syllables: [
          { value: "<", description: "mniej niż" },
          { value: "<=", description: "mniej niż lub równe" },
          { value: "=", description: "równy" },
          { value: ">=", description: "większy lub równy" },
          { value: ">", description: "większy niż" },
          { value: "!=", description: "nie równy" },
        ],
        stress: [
          { value: "<", description: "mniej niż" },
          { value: "<=", description: "mniej niż lub równe" },
          { value: "=", description: "równy" },
          { value: ">=", description: "większy lub równy" },
          { value: ">", description: "większy niż" },
          { value: "!=", description: "nie równy" },
        ],
        length: [
          { value: "<", description: "mniej niż" },
          { value: "<=", description: "mniej niż lub równe" },
          { value: "=", description: "równy" },
          { value: ">=", description: "większy lub równy" },
          { value: ">", description: "większy niż" },
          { value: "!=", description: "nie równy" },
        ],
      },
    } as ListMenu,
    and: "I...",
    go: "IDŹ",
    noResults: "brak wyników",
  },
  ru: {
    list: "Список",
    listOptions: "ПАРАМЕТРЫ СПИСКА",
    listMenu: {
      whatValues: [
        { value: "pos", description: "часть речи есть, имеет, и т. д." },
        {
          value: "word",
          description: "начинается, заканчивается, имеет, и т. д.",
        },
        {
          value: "words",
          description: "в порядке выхода, первый или последний",
        },
        { value: "syllables", description: "количество слогов" },
        { value: "stress", description: "позиция ударного слога" },
        { value: "length", description: "длина слова в фонемах" },
      ],
      condValues: {
        pos: [
          { value: "starts", description: "начинается с" },
          { value: "ends", description: "заканчивается" },
          { value: "is", description: "есть" },
          { value: "has", description: "имеет" },
          { value: "like", description: "похоже на" },
          { value: "not-starts", description: "не начинается с" },
          { value: "not-ends", description: "не заканчивается" },
          { value: "not-is", description: "не есть" },
          { value: "not-has", description: "не имеет" },
          { value: "not-like", description: "не похоже на" },
        ],
        word: [
          { value: "starts", description: "начинается с" },
          { value: "ends", description: "заканчивается" },
          { value: "has", description: "имеет" },
          { value: "like", description: "похоже на" },
          { value: "not-starts", description: "не начинается с" },
          { value: "not-ends", description: "не заканчивается" },
          { value: "not-has", description: "не имеет" },
          { value: "not-like", description: "не похоже на" },
        ],
        words: [
          { value: "first", description: "самые старые слова" },
          { value: "last", description: "самые новые слова" },
        ],
        syllables: [
          { value: "<", description: "меньше чем" },
          { value: "<=", description: "меньше или равно" },
          { value: "=", description: "равно" },
          { value: ">=", description: "больше или равно" },
          { value: ">", description: "больше чем" },
          { value: "!=", description: "не равно" },
        ],
        stress: [
          { value: "<", description: "меньше чем" },
          { value: "<=", description: "меньше или равно" },
          { value: "=", description: "равно" },
          { value: ">=", description: "больше или равно" },
          { value: ">", description: "больше чем" },
          { value: "!=", description: "не равно" },
        ],
        length: [
          { value: "<", description: "меньше чем" },
          { value: "<=", description: "меньше или равно" },
          { value: "=", description: "равно" },
          { value: ">=", description: "больше или равно" },
          { value: ">", description: "больше чем" },
          { value: "!=", description: "не равно" },
        ],
      },
    } as ListMenu,
    and: "И...",
    go: "ИДТИ",
    noResults: "нет результатов",
  },
  sv: {
    list: "Lista",
    listOptions: "LISTALTERNATIV",
    listMenu: {
      whatValues: [
        { value: "pos", description: "ordklass är, har, etc." },
        { value: "word", description: "börjar med, slutar med, har, etc." },
        {
          value: "words",
          description: "i ordning av utgåva, först eller sist",
        },
        { value: "syllables", description: "antal stavelser" },
        { value: "stress", description: "betonad stavelseposition" },
        { value: "length", description: "längd på ordet i fonem" },
      ],
      condValues: {
        pos: [
          { value: "starts", description: "börjar med" },
          { value: "ends", description: "slutar med" },
          { value: "is", description: "är" },
          { value: "has", description: "har" },
          { value: "like", description: "är som" },
          { value: "not-starts", description: "börjar inte med" },
          { value: "not-ends", description: "slutar inte med" },
          { value: "not-is", description: "är inte" },
          { value: "not-has", description: "har inte" },
          { value: "not-like", description: "är inte som" },
        ],
        word: [
          { value: "starts", description: "börjar med" },
          { value: "ends", description: "slutar med" },
          { value: "has", description: "har" },
          { value: "like", description: "är som" },
          { value: "not-starts", description: "börjar inte med" },
          { value: "not-ends", description: "slutar inte med" },
          { value: "not-has", description: "har inte" },
          { value: "not-like", description: "är inte som" },
        ],
        words: [
          { value: "first", description: "äldsta ord" },
          { value: "last", description: "nyaste ord" },
        ],
        syllables: [
          { value: "<", description: "mindre än" },
          { value: "<=", description: "mindre än eller lika med" },
          { value: "=", description: "lika med" },
          { value: ">=", description: "större än eller lika med" },
          { value: ">", description: "större än" },
          { value: "!=", description: "inte lika med" },
        ],
        stress: [
          { value: "<", description: "mindre än" },
          { value: "<=", description: "mindre än eller lika med" },
          { value: "=", description: "lika med" },
          { value: ">=", description: "större än eller lika med" },
          { value: ">", description: "större än" },
          { value: "!=", description: "inte lika med" },
        ],
        length: [
          { value: "<", description: "mindre än" },
          { value: "<=", description: "mindre än eller lika med" },
          { value: "=", description: "lika med" },
          { value: ">=", description: "större än eller lika med" },
          { value: ">", description: "större än" },
          { value: "!=", description: "inte lika med" },
        ],
      },
    } as ListMenu,
    and: "OCH...",
    go: "GÅ",
    noResults: "inga resultat",
  },
  tr: {
    list: "Liste",
    listOptions: "LİSTE SEÇENEKLERİ",
    listMenu: {
      whatValues: [
        { value: "pos", description: "konuşma parçası var, var, vb." },
        { value: "word", description: "ile başlar, ile biter, var, vb." },
        {
          value: "words",
          description: "çıkış sırasına göre, ilk veya son",
        },
        { value: "syllables", description: "hece sayısı" },
        { value: "stress", description: "vurgulu hece konumu" },
        { value: "length", description: "fonemlerde kelimenin uzunluğu" },
      ],
      condValues: {
        pos: [
          { value: "starts", description: "ile başlar" },
          { value: "ends", description: "ile biter" },
          { value: "is", description: "vardır" },
          { value: "has", description: "vardır" },
          { value: "like", description: "gibi" },
          { value: "not-starts", description: "ile başlamaz" },
          { value: "not-ends", description: "ile bitmez" },
          { value: "not-is", description: "değil" },
          { value: "not-has", description: "yok" },
          { value: "not-like", description: "gibi değil" },
        ],
        word: [
          { value: "starts", description: "ile başlar" },
          { value: "ends", description: "ile biter" },
          { value: "has", description: "vardır" },
          { value: "like", description: "gibi" },
          { value: "not-starts", description: "ile başlamaz" },
          { value: "not-ends", description: "ile bitmez" },
          { value: "not-has", description: "yok" },
          { value: "not-like", description: "gibi değil" },
        ],
        words: [
          { value: "first", description: "en eski kelimeler" },
          { value: "last", description: "en yeni kelimeler" },
        ],
        syllables: [
          { value: "<", description: "daha az" },
          { value: "<=", description: "daha az veya eşit" },
          { value: "=", description: "eşit" },
          { value: ">=", description: "daha büyük veya eşit" },
          { value: ">", description: "daha büyük" },
          { value: "!=", description: "eşit değil" },
        ],
        stress: [
          { value: "<", description: "daha az" },
          { value: "<=", description: "daha az veya eşit" },
          { value: "=", description: "eşit" },
          { value: ">=", description: "daha büyük veya eşit" },
          { value: ">", description: "daha büyük" },
          { value: "!=", description: "eşit değil" },
        ],
        length: [
          { value: "<", description: "daha az" },
          { value: "<=", description: "daha az veya eşit" },
          { value: "=", description: "eşit" },
          { value: ">=", description: "daha büyük veya eşit" },
          { value: ">", description: "daha büyük" },
          { value: "!=", description: "eşit değil" },
        ],
      },
    } as ListMenu,
    and: "VE...",
    go: "GIT",
    noResults: "sonuç yok",
  },
};

export default strings;
