import type { ExtendedLanguageCode } from "@/types/common";

type SearchStrings = {
  [key in ExtendedLanguageCode]: {
    search: string;
    audio: string;
    partOfSpeech: string;
    definition: string;
    breakdown: string;
    infixDots: string;
    infixSlots: string;
    prefixes: string;
    infixes: string;
    suffixes: string;
    lenition: string;
    comment: string;
    source: string;
    ipa: string;
  };
};

const strings: SearchStrings = {
  de: {
    search: "Suche",
    audio: "Audio",
    partOfSpeech: "Wortart",
    definition: "Definition",
    breakdown: "Silbentrennung",
    infixDots: "Infixe (Punkte)",
    infixSlots: "Infixe (Slots)",
    prefixes: "Präfixe",
    infixes: "Infixe",
    suffixes: "Suffixe",
    lenition: "Lenierung",
    comment: "Kommentar",
    source: "Quelle",
    ipa: "IPA",
  },
  en: {
    search: "Search",
    audio: "Audio",
    partOfSpeech: "Part of speech",
    definition: "Definition",
    breakdown: "Breakdown",
    infixDots: "Infixes (dots)",
    infixSlots: "Infixes (slots)",
    prefixes: "Prefixes",
    infixes: "Infixes",
    suffixes: "Suffixes",
    lenition: "Lenition",
    comment: "Comment",
    source: "Source",
    ipa: "IPA",
  },
  eo: {
    search: "Serĉi",
    audio: "Audio",
    partOfSpeech: "Vorttipo",
    definition: "Difino",
    breakdown: "Silaboj",
    infixDots: "Infixes (dots)",
    infixSlots: "Infixes (slots)",
    prefixes: "Prefiksoj",
    infixes: "Infixes",
    suffixes: "Sufiksoj",
    lenition: "Lenition",
    comment: "Komento",
    source: "Fonto",
    ipa: "IPA",
  },
  es: {
    search: "Busca",
    audio: "Audio",
    partOfSpeech: "Parte de la oración",
    definition: "Definición",
    breakdown: "Sílabas",
    infixDots: "Infijos (puntos)",
    infixSlots: "Infijs (slots)",
    prefixes: "Prefijos",
    infixes: "Infijes",
    suffixes: "Sufijos",
    lenition: "Lenición",
    comment: "Comentario",
    source: "Fuente",
    ipa: "IPA",
  },
  et: {
    search: "Otsing",
    audio: "Audio",
    partOfSpeech: "Sõnaliik",
    definition: "Definitsioon",
    breakdown: "Silbitus",
    infixDots: "Infixes (dots)",
    infixSlots: "Infixes (slots)",
    prefixes: "Eesliited",
    infixes: "Infixes",
    suffixes: "Tagasõnad",
    lenition: "Lenition",
    comment: "Kommentaar",
    source: "Allikas",
    ipa: "IPA",
  },
  fr: {
    search: "Recherche",
    audio: "Audio",
    partOfSpeech: "Partie du discours",
    definition: "Définition",
    breakdown: "Syllabes",
    infixDots: "Infixes (points)",
    infixSlots: "Infixes (slots)",
    prefixes: "Préfixes",
    infixes: "Infixes",
    suffixes: "Suffixes",
    lenition: "Lenition",
    comment: "Commentaire",
    source: "Source",
    ipa: "API",
  },
  hu: {
    search: "Keresés",
    audio: "Audio",
    partOfSpeech: "Szófaj",
    definition: "Definíció",
    breakdown: "Szótagolás",
    infixDots: "Infixes (dots)",
    infixSlots: "Infixes (slots)",
    prefixes: "Előtagok",
    infixes: "Infixes",
    suffixes: "Utótagok",
    lenition: "Lenition",
    comment: "Megjegyzés",
    source: "Forrás",
    ipa: "IPA",
  },
  nl: {
    search: "Zoeken",
    audio: "Audio",
    partOfSpeech: "Woordsoort",
    definition: "Definitie",
    breakdown: "Lettergrepen",
    infixDots: "Tussenvoegsels (dots)",
    infixSlots: "Tussenvoegsels (slots)",
    prefixes: "Voorvoegsels",
    infixes: "Tussenvoegsels",
    suffixes: "Achtervoegsels",
    lenition: "Lenitie",
    comment: "Commentaar",
    source: "Bron",
    ipa: "IPA",
  },
  nx: {
    search: "fwew",
    audio: "Pam",
    partOfSpeech: "fnelì'u",
    definition: "ral",
    breakdown: "pamä tìlatem",
    infixDots: "kemlì'uvi",
    infixSlots: "kemlì'uvi",
    prefixes: "eolì'uvi",
    infixes: "kemlì'uvi",
    suffixes: "uolì'uvi",
    lenition: "pamä tìlatem",
    comment: "säplltxevi",
    source: "tsim",
    ipa: "IPA",
  },
  pl: {
    search: "Szukaj",
    audio: "Audio",
    partOfSpeech: "Część mowy",
    definition: "Definicja",
    breakdown: "Podział na sylaby",
    infixDots: "Infixes (dots)",
    infixSlots: "Infixes (slots)",
    prefixes: "Prefiksy",
    infixes: "Infixes",
    suffixes: "Sufiksy",
    lenition: "Lenition",
    comment: "Komentarz",
    source: "Źródło",
    ipa: "IPA",
  },
  pt: {
    search: "Procurar",
    audio: "Audio",
    partOfSpeech: "Classe gramatical",
    definition: "Definição",
    breakdown: "Separação sílabica",
    infixDots: "Infixos (pontos)",
    infixSlots: "Infixos (posição)",
    prefixes: "Prefixos",
    infixes: "Infixos",
    suffixes: "Sufixos",
    lenition: "Lenição",
    comment: "Comentário",
    source: "Fonte",
    ipa: "IPA",
  },
  ru: {
    search: "Поиск",
    audio: "Audio",
    partOfSpeech: "Часть речи",
    definition: "Определение",
    breakdown: "Разбивка на слоги",
    infixDots: "Infixes (dots)",
    infixSlots: "Infixes (slots)",
    prefixes: "Префиксы",
    infixes: "Infixes",
    suffixes: "Суффиксы",
    lenition: "Lenition",
    comment: "Комментарий",
    source: "Источник",
    ipa: "IPA",
  },
  sv: {
    search: "Sök",
    audio: "Audio",
    partOfSpeech: "Ordklass",
    definition: "Definition",
    breakdown: "Orddelning",
    infixDots: "Infixes (dots)",
    infixSlots: "Infixes (slots)",
    prefixes: "Prefixes",
    infixes: "Infixes",
    suffixes: "Suffixes",
    lenition: "Lenition",
    comment: "Kommentar",
    source: "Källa",
    ipa: "IPA",
  },
  tr: {
    search: "Ara",
    audio: "Audio",
    partOfSpeech: "Konuşmanın bölümü",
    definition: "Tanım",
    breakdown: "Heceler",
    infixDots: "Düzeltmeler (noktaları)",
    infixSlots: "Düzeltmeler (yerleri)",
    prefixes: "Önekler",
    infixes: "Düzeltmeler",
    suffixes: "Son ekler",
    lenition: "Cömertlik",
    comment: "Yorum",
    source: "Kaynak",
    ipa: "IPA",
  },
};

export default strings;
